function handles = Plot_Casing_Data(data);
%
% Plot_Casing_Data(data)
%
% A function to plot the data generated by resample data

figure
hold on

v= [0.6:0.02:1.2];

plot(data.blade(:,6),data.blade(:,1),'k');
plot(data.blade(:,6)-data.repeat*mean(data.blade(:,4)),data.blade(:,1),'k');

[handles.CS,handles.H] = contourf(data.casing.s_target,data.casing.x_target,data.casing.data_target,v);
axis equal
axis off

caxis([0.6 1.2]);
handles.bar = colorbar('horiz'); 

plot(data.blade(:,6),data.blade(:,1),'k');
plot(data.blade(:,6)-data.repeat*mean(data.blade(:,4)),data.blade(:,1),'k');