c
      FUNCTION MPI_WTIME()
      RETURN
      END
C
      SUBROUTINE MPI_FINALIZE(A)
      RETURN
      END
C
      SUBROUTINE MPI_INIT(A)
      RETURN
      END
C     
      SUBROUTINE MPI_COMM_RANK(A,B,C)
      RETURN
      END
C     
      SUBROUTINE MPI_COMM_SIZE(A,B,C)
      RETURN
      END
C
      SUBROUTINE MPI_BCAST(A,B,C,D,E,F)
      RETURN
      END
C
      SUBROUTINE MPI_BARRIER(A,B)
      RETURN
      END
C
      SUBROUTINE MPI_ALLGATHER(A,B,C,D,E,F,G,H)
      RETURN
      END
C
      SUBROUTINE MPI_GATHER(A,B,C,D,E,F,G)
      RETURN
      END

C
      SUBROUTINE MPI_REDUCE(A,B,C,D,E,F,G,H)
      RETURN
      END
C
      SUBROUTINE MPI_ISEND(A,B,C,D,E,F,G,H)
      RETURN
      END
C
      SUBROUTINE MPI_IRECV(A,B,C,D,E,F,G,H)
      RETURN
      END
C
      SUBROUTINE MPI_WAITALL(A,B,C,D)
      RETURN
      END
C
      SUBROUTINE MPI_TYPE_COMMIT(A,B)
      RETURN
      END
C
      SUBROUTINE MPI_TYPE_FREE(A,B)
      RETURN
      END
C
      SUBROUTINE MPI_ALLREDUCE(A,B,C,D,E,F,G)
      RETURN
      END
C
      SUBROUTINE MPI_TYPE_VECTOR(A,B,C,D,E,F)
      RETURN
      END
C
      SUBROUTINE MPI_TYPE_EXTENT(A,B,C)
      RETURN
      END
C
      SUBROUTINE MPI_TYPE_HVECTOR(A,B,C,D,E,F)
      RETURN
      END
C
      SUBROUTINE MPI_WAIT(A,B,C)
      RETURN
      END
      
